export const SET_PERMISSIONS = 'app.SET_PERMISSIONS';
export const INITIALIZE_AUTH = 'app.INITIALIZE_AUTH';
export const RECEIVE_OTHER_ACCOUNTS = 'app.RECEIVE_OTHER_ACCOUNTS';
export const BEGIN_ACCOUNT_CHANGE = 'app.BEGIN_ACCOUNT_CHANGE';
export const END_ACCOUNT_CHANGE = 'app.END_ACCOUNT_CHANGE';
export const LOG_OUT = 'app.LOG_OUT';
export const OPEN_MENU = 'app.OPEN_MENU';
export const CLOSE_MENU = 'app.CLOSE_MENU';
export const OPEN_DEBUG_VIEW = 'app.OPEN_DEBUG_VIEW';
export const CLOSE_DEBUG_VIEW = 'app.CLOSE_DEBUG_VIEW';
export const OPEN_FEATURES_VIEW = 'app.OPEN_FEATURES_VIEW';
export const CLOSE_FEATURES_VIEW = 'app.CLOSE_FEATURES_VIEW';
export const OPEN_SCAN_VIEW = 'app.OPEN_SCAN_VIEW';
export const CLOSE_SCAN_VIEW = 'app.CLOSE_SCAN_VIEW';
export const SET_FEATURES = 'app.SET_FEATURES';
export const ON_NAVIGATE_BACK = 'app.ON_NAVIGATE_BACK';

export const SHOW_USER_AGREEMENT = 'app.SHOW_USER_AGREEMENT';
export const HIDE_USER_AGREEMENT = 'app.HIDE_USER_AGREEMENT';

export const RECEIVE_WORK_TIME_SETTINGS = 'app.RECEIVE_WORK_TIME_SETTINGS';

export const RECEIVE_USER = 'app.RECEIVE_USER';
export const RECEIVE_USER_APPEARANCE_PROFILE = 'app.RECEIVE_USER_APPEARANCE_PROFILE';
