# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Disable New Architecture (Fabric) for compatibility with existing dependencies
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport = true

use_frameworks! :linkage => :static

def patch_fmt_for_xcode_26
  fmt_header = File.join(
    __dir__,
    'Pods',
    'fmt',
    'include',
    'fmt',
    'base.h'
  )

  unless File.exist?(fmt_header)
    raise "fmt header was not found: #{fmt_header}"
  end

  old_code =
    '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L'

  new_code =
    '#elif defined(__apple_build_version__)'

  content = File.read(fmt_header)

  if content.include?(old_code)
    patched_content = content.sub(old_code, new_code)
    File.write(fmt_header, patched_content)

    Pod::UI.puts 'Applied fmt compatibility patch for Xcode 26'.green
  elsif content.include?(new_code)
    Pod::UI.puts 'fmt compatibility patch is already applied'.green
  else
    raise <<~MESSAGE
      Unable to apply the fmt Xcode 26 compatibility patch.

      The expected code was not found in:
      #{fmt_header}

      The fmt dependency may have changed. Review the patch before continuing.
    MESSAGE
  end
end

target 'YouTrackMobile' do
  config = use_native_modules!
  
  Pod::UI.puts "RCT_BUILD_HERMES_FROM_SOURCE=#{ENV['RCT_BUILD_HERMES_FROM_SOURCE'].inspect}".yellow
  Pod::UI.puts "REACT_NATIVE_OVERRIDE_HERMES_DIR=#{ENV['REACT_NATIVE_OVERRIDE_HERMES_DIR'].inspect}".yellow
  Pod::UI.puts "HERMES_ENGINE_TARBALL_PATH=#{ENV['HERMES_ENGINE_TARBALL_PATH'].inspect}".yellow

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true
  )

  target 'YouTrackMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    patch_fmt_for_xcode_26
  end
end
