export const LOAD_BOARD = 'LOAD_BOARD';
export const START_SPRINT_LOADING = 'START_SPRINT_LOADING';
export const STOP_SPRINT_LOADING = 'STOP_SPRINT_LOADING';
export const RECEIVE_SPRINT = 'RECEIVE_SPRINT';
