export const routeMap = {
  AgileBoard: 'AgileBoard',
  Article: 'Article',
  ArticleSingle: 'ArticleSingle',
  ArticleCreate: 'ArticleCreate',
  KnowledgeBase: 'KnowledgeBase',
  AttachmentPreview: 'AttachmentPreview',
  CreateIssue: 'CreateIssue',
  EnterServer: 'EnterServer',
  Home: 'Home',
  Inbox: 'Inbox',
  InboxThreads: 'InboxThreads',
  Issues: 'Issues',
  LogIn: 'LogIn',
  Page: 'Page',
  PageModal: 'PageModal',
  Settings: 'Settings',
  Modal: 'Modal',
  PreviewFile: 'PreviewFile',
  Issue: 'Issue',
  Issue2: 'Issue2',
  WikiPage: 'WikiPage',
  Tickets: 'Tickets',
};
export const rootRoutesList = [
  routeMap.Issues,
  routeMap.Tickets,
  routeMap.AgileBoard,
  routeMap.Inbox,
  routeMap.InboxThreads,
  routeMap.Settings,
  routeMap.KnowledgeBase,
  routeMap.ArticleSingle,
];
